apiVersion: v1
kind: Namespace
metadata:
  name: voice-agent
  labels:
    name: voice-agent
---
apiVersion: v1
kind: Secret
metadata:
  name: voice-agent-secrets
  namespace: voice-agent
type: Opaque
data:
  # Base64 encoded secrets - will be populated by CI/CD
  supabase-url: ""
  supabase-anon-key: ""
  supabase-service-role-key: ""
  jwt-secret: ""
  openai-api-key: ""
  openai-endpoint: ""
  redis-url: ""
  postgres-connection-string: ""
  storage-connection-string: ""
  twilio-account-sid: ""
  twilio-auth-token: ""
  twilio-phone-number: ""
  vonage-api-key: ""
  vonage-api-secret: ""
  vonage-application-id: ""
  vonage-private-key: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: voice-agent-config
  namespace: voice-agent
data:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  SECTOR: "generic"
  VOICE_PROVIDER: "twilio"
  CORS_ORIGIN: "*"
  CHROMA_PERSIST_DIRECTORY: "/app/chroma_db"
  DISABLE_OPTIMIZATIONS: "false"
  PORT: "3000"
  HOST: "0.0.0.0"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voice-agent-orchestrator
  namespace: voice-agent
  labels:
    app: voice-agent-orchestrator
    version: v1
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: voice-agent-orchestrator
  template:
    metadata:
      labels:
        app: voice-agent-orchestrator
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: orchestrator
        image: voiceagentregistry.azurecr.io/voice-agent-orchestrator:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: voice-agent-config
              key: NODE_ENV
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: voice-agent-config
              key: LOG_LEVEL
        - name: SECTOR
          valueFrom:
            configMapKeyRef:
              name: voice-agent-config
              key: SECTOR
        - name: CHROMA_PERSIST_DIRECTORY
          valueFrom:
            configMapKeyRef:
              name: voice-agent-config
              key: CHROMA_PERSIST_DIRECTORY
        - name: DISABLE_OPTIMIZATIONS
          valueFrom:
            configMapKeyRef:
              name: voice-agent-config
              key: DISABLE_OPTIMIZATIONS
        - name: SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: voice-agent-secrets
              key: supabase-url
        - name: SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: voice-agent-secrets
              key: supabase-anon-key
        - name: SUPABASE_SERVICE_ROLE_KEY
          valueFrom:
            secretKeyRef:
              name: voice-agent-secrets
              key: supabase-service-role-key
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: voice-agent-secrets
              key: jwt-secret
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: voice-agent-secrets
              key: openai-api-key
        - name: OPENAI_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: voice-agent-secrets
              key: openai-endpoint
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: voice-agent-secrets
              key: redis-url
        - name: POSTGRES_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: voice-agent-secrets
              key: postgres-connection-string
        - name: STORAGE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: voice-agent-secrets
              key: storage-connection-string
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: chroma-data
          mountPath: /app/chroma_db
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: chroma-data
        persistentVolumeClaim:
          claimName: chroma-data-pvc
      - name: logs
        emptyDir: {}
      imagePullSecrets:
      - name: acr-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voice-agent-realtime
  namespace: voice-agent
  labels:
    app: voice-agent-realtime
    version: v1
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: voice-agent-realtime
  template:
    metadata:
      labels:
        app: voice-agent-realtime
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: realtime
        image: voiceagentregistry.azurecr.io/voice-agent-realtime:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: voice-agent-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: voice-agent-config
              key: PORT
        - name: HOST
          valueFrom:
            configMapKeyRef:
              name: voice-agent-config
              key: HOST
        - name: VOICE_PROVIDER
          valueFrom:
            configMapKeyRef:
              name: voice-agent-config
              key: VOICE_PROVIDER
        - name: CORS_ORIGIN
          valueFrom:
            configMapKeyRef:
              name: voice-agent-config
              key: CORS_ORIGIN
        - name: ORCHESTRATOR_URL
          value: "http://voice-agent-orchestrator-service:80"
        - name: SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: voice-agent-secrets
              key: supabase-url
        - name: SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: voice-agent-secrets
              key: supabase-anon-key
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: voice-agent-secrets
              key: jwt-secret
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: voice-agent-secrets
              key: redis-url
        - name: TWILIO_ACCOUNT_SID
          valueFrom:
            secretKeyRef:
              name: voice-agent-secrets
              key: twilio-account-sid
        - name: TWILIO_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: voice-agent-secrets
              key: twilio-auth-token
        - name: TWILIO_PHONE_NUMBER
          valueFrom:
            secretKeyRef:
              name: voice-agent-secrets
              key: twilio-phone-number
        - name: VONAGE_API_KEY
          valueFrom:
            secretKeyRef:
              name: voice-agent-secrets
              key: vonage-api-key
        - name: VONAGE_API_SECRET
          valueFrom:
            secretKeyRef:
              name: voice-agent-secrets
              key: vonage-api-secret
        - name: VONAGE_APPLICATION_ID
          valueFrom:
            secretKeyRef:
              name: voice-agent-secrets
              key: vonage-application-id
        - name: VONAGE_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: voice-agent-secrets
              key: vonage-private-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: logs
        emptyDir: {}
      imagePullSecrets:
      - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: voice-agent-orchestrator-service
  namespace: voice-agent
  labels:
    app: voice-agent-orchestrator
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: voice-agent-orchestrator
---
apiVersion: v1
kind: Service
metadata:
  name: voice-agent-realtime-service
  namespace: voice-agent
  labels:
    app: voice-agent-realtime
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: voice-agent-realtime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chroma-data-pvc
  namespace: voice-agent
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: managed-csi
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: voice-agent-orchestrator-pdb
  namespace: voice-agent
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: voice-agent-orchestrator
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: voice-agent-realtime-pdb
  namespace: voice-agent
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: voice-agent-realtime
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: voice-agent-orchestrator-hpa
  namespace: voice-agent
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: voice-agent-orchestrator
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: voice-agent-realtime-hpa
  namespace: voice-agent
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: voice-agent-realtime
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
